[2022-04-11 14:34:00,977] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform manual__2022-04-11T14:28:35.187138+00:00 [queued]>
[2022-04-11 14:34:01,022] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform manual__2022-04-11T14:28:35.187138+00:00 [queued]>
[2022-04-11 14:34:01,023] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:34:01,025] {taskinstance.py:1250} INFO - Starting attempt 2 of 3
[2022-04-11 14:34:01,027] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:34:01,075] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform> on 2022-04-11 14:28:35.187138+00:00
[2022-04-11 14:34:01,085] {standard_task_runner.py:52} INFO - Started process 6398 to run task
[2022-04-11 14:34:01,095] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform', 'manual__2022-04-11T14:28:35.187138+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmpmvl5skvl', '--error-file', '/tmp/tmphplbpr9s']
[2022-04-11 14:34:01,098] {standard_task_runner.py:80} INFO - Job 67: Subtask transform
[2022-04-11 14:34:01,250] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform manual__2022-04-11T14:28:35.187138+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:34:01,396] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:28:35.187138+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:28:35.187138+00:00
[2022-04-11 14:34:13,347] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (11,15,32,38,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-11 14:34:14,057] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 14:34:14,097] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform, execution_date=20220411T142835, start_date=20220411T143400, end_date=20220411T143414
[2022-04-11 14:34:14,207] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 14:34:14,364] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
