[2022-04-11 14:22:02,824] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:21:53.941443+00:00 [queued]>
[2022-04-11 14:22:02,891] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:21:53.941443+00:00 [queued]>
[2022-04-11 14:22:02,894] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:22:02,896] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 14:22:02,897] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:22:02,959] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:21:53.941443+00:00
[2022-04-11 14:22:02,976] {standard_task_runner.py:52} INFO - Started process 5694 to run task
[2022-04-11 14:22:02,994] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:21:53.941443+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp8umqpz5w', '--error-file', '/tmp/tmpus332vdt']
[2022-04-11 14:22:02,998] {standard_task_runner.py:80} INFO - Job 52: Subtask extract
[2022-04-11 14:22:03,199] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:21:53.941443+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:22:03,418] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:21:53.941443+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:21:53.941443+00:00
[2022-04-11 14:25:42,988] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 14:25:43,038] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=extract, execution_date=20220411T142153, start_date=20220411T142202, end_date=20220411T142543
[2022-04-11 14:25:43,185] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 14:25:43,267] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
