[2022-04-11 13:00:11,437] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform manual__2022-04-11T12:59:52.819057+00:00 [queued]>
[2022-04-11 13:00:11,489] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.transform manual__2022-04-11T12:59:52.819057+00:00 [queued]>
[2022-04-11 13:00:11,491] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 13:00:11,497] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 13:00:11,500] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 13:00:11,591] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): transform> on 2022-04-11 12:59:52.819057+00:00
[2022-04-11 13:00:11,602] {standard_task_runner.py:52} INFO - Started process 1332 to run task
[2022-04-11 13:00:11,624] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'transform', 'manual__2022-04-11T12:59:52.819057+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp51x32re6', '--error-file', '/tmp/tmp8f3lm1lv']
[2022-04-11 13:00:11,629] {standard_task_runner.py:80} INFO - Job 19: Subtask transform
[2022-04-11 13:00:11,825] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.transform manual__2022-04-11T12:59:52.819057+00:00 [running]> on host 474cd328f92b
[2022-04-11 13:00:12,015] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T12:59:52.819057+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T12:59:52.819057+00:00
[2022-04-11 13:00:12,080] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 13:00:12,164] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=transform, execution_date=20220411T125952, start_date=20220411T130011, end_date=20220411T130012
[2022-04-11 13:00:12,314] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 13:00:12,566] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
