[2022-04-11 12:22:54,516] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.load manual__2022-04-11T12:22:31.003924+00:00 [queued]>
[2022-04-11 12:22:54,570] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.load manual__2022-04-11T12:22:31.003924+00:00 [queued]>
[2022-04-11 12:22:54,572] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:22:54,574] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 12:22:54,577] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:22:54,659] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): load> on 2022-04-11 12:22:31.003924+00:00
[2022-04-11 12:22:54,668] {standard_task_runner.py:52} INFO - Started process 314 to run task
[2022-04-11 12:22:54,693] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'load', 'manual__2022-04-11T12:22:31.003924+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmpvukrqhvg', '--error-file', '/tmp/tmp41xg5fd8']
[2022-04-11 12:22:54,699] {standard_task_runner.py:80} INFO - Job 14: Subtask load
[2022-04-11 12:22:54,962] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.load manual__2022-04-11T12:22:31.003924+00:00 [running]> on host 474cd328f92b
[2022-04-11 12:22:55,198] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T12:22:31.003924+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T12:22:31.003924+00:00
[2022-04-11 12:22:55,237] {logging_mixin.py:109} INFO - {'total_order_value': 1236.7}
[2022-04-11 12:22:55,239] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 12:22:55,346] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=load, execution_date=20220411T122231, start_date=20220411T122254, end_date=20220411T122255
[2022-04-11 12:22:55,492] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 12:22:55,686] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
