[2022-04-11 12:52:11,600] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T12:52:06.780068+00:00 [queued]>
[2022-04-11 12:52:11,664] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T12:52:06.780068+00:00 [queued]>
[2022-04-11 12:52:11,673] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:52:11,676] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 12:52:11,677] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:52:11,751] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 12:52:06.780068+00:00
[2022-04-11 12:52:11,760] {standard_task_runner.py:52} INFO - Started process 895 to run task
[2022-04-11 12:52:11,777] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T12:52:06.780068+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp6s1ihb9w', '--error-file', '/tmp/tmpormvim4y']
[2022-04-11 12:52:11,781] {standard_task_runner.py:80} INFO - Job 15: Subtask extract
[2022-04-11 12:52:11,975] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T12:52:06.780068+00:00 [running]> on host 474cd328f92b
[2022-04-11 12:52:12,218] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T12:52:06.780068+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T12:52:06.780068+00:00
[2022-04-11 12:52:17,873] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:188: DtypeWarning: Columns (3,7,14,15,16,17,18,21,22,24,25) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2022-04-11 12:52:17,944] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 12:52:17,981] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=extract, execution_date=20220411T125206, start_date=20220411T125211, end_date=20220411T125217
[2022-04-11 12:52:18,041] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 12:52:18,162] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
