[2022-04-11 14:00:37,964] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:00:33.398865+00:00 [queued]>
[2022-04-11 14:00:38,010] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:00:33.398865+00:00 [queued]>
[2022-04-11 14:00:38,012] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:00:38,013] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 14:00:38,014] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:00:38,062] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:00:33.398865+00:00
[2022-04-11 14:00:38,072] {standard_task_runner.py:52} INFO - Started process 4458 to run task
[2022-04-11 14:00:38,081] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:00:33.398865+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmptii95xfr', '--error-file', '/tmp/tmp0bie1mx3']
[2022-04-11 14:00:38,085] {standard_task_runner.py:80} INFO - Job 22: Subtask extract
[2022-04-11 14:00:38,275] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:00:33.398865+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:00:38,553] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:00:33.398865+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:00:33.398865+00:00
[2022-04-11 14:00:43,780] {xcom.py:448} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-04-11 14:00:43,785] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/try.py", line 44, in extract
    ti.xcom_push('data_frame', df_all)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2207, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 155, in set
    value=cls.serialize_value(value),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 445, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-04-11 14:00:43,830] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=openDataETL, task_id=extract, execution_date=20220411T140033, start_date=20220411T140037, end_date=20220411T140043
[2022-04-11 14:00:43,879] {standard_task_runner.py:98} ERROR - Failed to execute job 22 for task extract (Object of type DataFrame is not JSON serializable; 4458)
[2022-04-11 14:00:43,919] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 14:00:44,038] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
