[2022-04-11 12:22:44,337] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T12:22:31.003924+00:00 [queued]>
[2022-04-11 12:22:44,386] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T12:22:31.003924+00:00 [queued]>
[2022-04-11 12:22:44,389] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:22:44,391] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 12:22:44,392] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 12:22:44,445] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 12:22:31.003924+00:00
[2022-04-11 12:22:44,454] {standard_task_runner.py:52} INFO - Started process 294 to run task
[2022-04-11 12:22:44,464] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T12:22:31.003924+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmpn6galeck', '--error-file', '/tmp/tmp19x5e6zt']
[2022-04-11 12:22:44,467] {standard_task_runner.py:80} INFO - Job 12: Subtask extract
[2022-04-11 12:22:44,601] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T12:22:31.003924+00:00 [running]> on host 474cd328f92b
[2022-04-11 12:22:44,759] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T12:22:31.003924+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T12:22:31.003924+00:00
[2022-04-11 12:22:44,792] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 12:22:44,838] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=extract, execution_date=20220411T122231, start_date=20220411T122244, end_date=20220411T122244
[2022-04-11 12:22:44,917] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 12:22:45,055] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
