[2022-04-11 14:15:55,903] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:15:49.853087+00:00 [queued]>
[2022-04-11 14:15:55,952] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: openDataETL.extract manual__2022-04-11T14:15:49.853087+00:00 [queued]>
[2022-04-11 14:15:55,954] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:15:55,955] {taskinstance.py:1250} INFO - Starting attempt 1 of 3
[2022-04-11 14:15:55,957] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 14:15:56,017] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): extract> on 2022-04-11 14:15:49.853087+00:00
[2022-04-11 14:15:56,038] {standard_task_runner.py:52} INFO - Started process 5300 to run task
[2022-04-11 14:15:56,060] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'openDataETL', 'extract', 'manual__2022-04-11T14:15:49.853087+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/try.py', '--cfg-path', '/tmp/tmp5rhqeizp', '--error-file', '/tmp/tmpfgefwfbd']
[2022-04-11 14:15:56,077] {standard_task_runner.py:80} INFO - Job 32: Subtask extract
[2022-04-11 14:15:56,362] {logging_mixin.py:109} INFO - Running <TaskInstance: openDataETL.extract manual__2022-04-11T14:15:49.853087+00:00 [running]> on host 474cd328f92b
[2022-04-11 14:15:56,633] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=openDataETL
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T14:15:49.853087+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-11T14:15:49.853087+00:00
[2022-04-11 14:15:59,078] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 14:15:59,118] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=openDataETL, task_id=extract, execution_date=20220411T141549, start_date=20220411T141555, end_date=20220411T141559
[2022-04-11 14:15:59,238] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 14:15:59,392] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
